import Head from "next/head";
import { CircularPacking } from "../components/CircularPacking";
import styles from "../styles/Home.module.css";
import { data } from "../data/data";
import { useState } from "react";

const buttonStyle = {
  border: "1px solid #9a6fb0",
  borderRadius: "3px",
  padding: "4px 8px",
  margin: "10px 2px",
  fontSize: 14,
  color: "#9a6fb0",
};

export default function Home() {
  const [type, setType] = useState<
    "circlepack" | "barplot" | "treemap" | "dendrogram"
  >("circlepack");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button style={buttonStyle} onClick={() => setType("circlepack")}>
            Circlepack
          </button>
          <button style={buttonStyle} onClick={() => setType("barplot")}>
            Barplot
          </button>
          <button style={buttonStyle} onClick={() => setType("treemap")}>
            Treemap
          </button>
          <button style={buttonStyle} onClick={() => setType("dendrogram")}>
            Dendrogram
          </button>
        </div>

        <CircularPacking width={900} height={600} data={data} type={type} />
      </main>

      <footer className={styles.footer}>Powered by Yan Holtz </footer>
    </div>
  );
}
