import Head from "next/head";
import { CircularPacking } from "../components/CircularPacking";
import styles from "../styles/Home.module.css";
import { data } from "../data/data";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CircularPacking width={900} height={800} data={data} />
      </main>

      <footer className={styles.footer}>Powered by Yan Holtz </footer>
    </div>
  );
}
